name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (e.g., basic-app)'
        required: true
        default: 'basic-app'

jobs:
  docker:
    concurrency:
      group: dev-development
      cancel-in-progress: false
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -f ./basic-app/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/basic-app:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/basic-app:${{ github.sha }}
